version: "3.8"

services:
  app:
    build: .
    container_name: node_app
    restart: unless-stopped
    ports:
      - "${APP_PORT}:3000"
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
      - /app/node_modules
    healthcheck:
      test: ["CMD", "node", "healthcheck.js"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    command: ["node", "server.js"]
    environment:
      - NODE_ENV=${NODE_ENV}
      - HOST=0.0.0.0
      - PORT=${APP_PORT}
      - APP_NAME=${APP_NAME}
      - APP_PHONE_NUMBER=${APP_PHONE_NUMBER}
      - SECRET=${SECRET}
      - DATABASE_URL=${DATABASE_URL}
      - BUCKET_STORAGE_URL=${BUCKET_STORAGE_URL}
      - FIREBASE_SERVICE_ACCOUNT_BASE64=${FIREBASE_SERVICE_ACCOUNT_BASE64}
      - PAYPAL_CLIENT_ID=${PAYPAL_CLIENT_ID}
      - PAYPAL_CLIENT_SECRET=${PAYPAL_CLIENT_SECRET}
      - MONGO_USER=${MONGO_USER}
      - MONGO_PASSWORD=${MONGO_PASSWORD}

